# Generated by Django 5.2.1 on 2026-05-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_passwordchangerequired"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitationtoken",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Propietario"),
                    ("admin", "Administrador"),
                    ("doctor", "Doctor"),
                    ("support", "Soporte"),
                    ("staff", "Staff"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Propietario"),
                    ("admin", "Administrador"),
                    ("doctor", "Doctor"),
                    ("support", "Soporte"),
                    ("staff", "Staff"),
                ],
                max_length=20,
            ),
        ),
    ]
