# Generated by Django 5.2.1 on 2026-05-06 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0006_plan_flags_paypal_fields"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformsettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("subscription_created", "Suscripción creada"),
                            ("subscription_activated", "Suscripción activada"),
                            ("subscription_cancelled", "Suscripción cancelada"),
                            ("subscription_suspended", "Suscripción suspendida"),
                            ("payment_completed", "Pago cobrado"),
                            ("payment_failed", "Pago fallido"),
                            ("other", "Otro"),
                        ],
                        max_length=40,
                    ),
                ),
                ("provider", models.CharField(default="paypal", max_length=20)),
                (
                    "provider_event_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "provider_subscription_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, default="", max_length=3)),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cuerpo crudo del evento o respuesta",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="platform.plan",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="platform.subscription",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción de pago",
                "verbose_name_plural": "Transacciones de pago",
                "db_table": "platform_payment_transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
