# Generated by Django 5.2.1 on 2026-05-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "plan",
                    models.CharField(
                        blank=True,
                        help_text="Plan que le interesó (gratuito, profesional, clinica, enterprise).",
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        default="marketing",
                        help_text="De dónde vino el lead (marketing, precios, etc.).",
                        max_length=80,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "leads",
                "ordering": ["-created_at"],
            },
        ),
    ]
