# Generated by Django 5.2.1 on 2026-05-05 03:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=63, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('solo', 'Doctor independiente'), ('clinic', 'Clínica')], default='solo', max_length=20)),
                ('plan', models.CharField(default='free', max_length=50)),
                ('custom_domain', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settings', models.JSONField(default=dict, help_text='Branding, timezone, locale, and feature flags per tenant.')),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['name'],
            },
        ),
    ]
