# Generated by Django 5.2.1 on 2026-05-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Resumen corto de la conversación, generado por IA al cerrar.",
                max_length=120,
            ),
        ),
    ]
