# Generated by Django 5.2.1 on 2026-05-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_conversation_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachment",
            field=models.ImageField(
                blank=True, null=True, upload_to="chat_attachments/"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
    ]
