# Generated by Django 5.2.1 on 2026-05-26 09:18

import apps.patients.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Femenino'), ('other', 'Otro'), ('undisclosed', 'Prefiero no decir')], max_length=20)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Desconocido')], max_length=10)),
                ('allergies', models.TextField(blank=True, help_text='Alergias conocidas (medicamentos, alimentos, etc.)')),
                ('current_medications', models.TextField(blank=True, help_text='Medicamentos que toma actualmente')),
                ('medical_conditions', models.TextField(blank=True, help_text='Condiciones crónicas o relevantes')),
                ('address_street', models.CharField(blank=True, max_length=200)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('address_state', models.CharField(blank=True, max_length=100)),
                ('address_zip', models.CharField(blank=True, max_length=10)),
                ('address_country', models.CharField(blank=True, default='México', max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relation', models.CharField(blank=True, help_text='Ej. Madre, Cónyuge, Hermano', max_length=50)),
                ('curp', models.CharField(blank=True, db_index=True, max_length=18)),
                ('rfc', models.CharField(blank=True, max_length=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientActivationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(default=apps.patients.models._default_activation_expires)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_activation_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de activación de paciente',
                'verbose_name_plural': 'Tokens de activación de pacientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
