# Generated by Django 5.2.1 on 2026-05-26 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address_zip',
            field=models.CharField(blank=True, help_text='5 dígitos.', max_length=5, validators=[django.core.validators.RegexValidator(code='invalid_zip_mx', message='Código postal inválido. Debe tener 5 dígitos.', regex='^\\d{5}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='curp',
            field=models.CharField(blank=True, db_index=True, help_text='18 caracteres. Ej. PEPJ800101HDFRRR01', max_length=18, validators=[django.core.validators.RegexValidator(code='invalid_curp', message='CURP inválido. Debe tener 18 caracteres con el formato oficial (ej. PEPJ800101HDFRRR01).', regex='^[A-Z]{4}\\d{6}[HM][A-Z]{5}[0-9A-Z]\\d$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='10 dígitos (con lada).', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phone_mx', message='Teléfono inválido. Debe tener 10 dígitos (lada incluida).', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, help_text='10 dígitos (con lada). Ej. 5512345678', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phone_mx', message='Teléfono inválido. Debe tener 10 dígitos (lada incluida).', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rfc',
            field=models.CharField(blank=True, help_text='13 caracteres. Ej. PEPJ800101AB1', max_length=13, validators=[django.core.validators.RegexValidator(code='invalid_rfc', message='RFC inválido. Debe tener 13 caracteres para persona física (ej. PEPJ800101AB1).', regex='^[A-ZÑ&]{4}\\d{6}[0-9A-Z]{3}$')]),
        ),
    ]
