# Generated by Django 5.2.1 on 2026-05-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_address_zip_alter_patient_curp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address_neighborhood',
            field=models.CharField(blank=True, help_text='Colonia o asentamiento (ej. Palo de Rosa, Roma Norte).', max_length=120),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address_city',
            field=models.CharField(blank=True, help_text='Ciudad o municipio (ej. Ciudad Valles, CDMX).', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address_street',
            field=models.CharField(blank=True, help_text='Calle, número exterior y opcional interior.', max_length=200),
        ),
    ]
