# Generated by Django 5.2.1 on 2026-05-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="blood_pressure",
            field=models.CharField(blank=True, help_text="Ej. 120/80", max_length=15),
        ),
        migrations.AddField(
            model_name="appointment",
            name="clinical_notes",
            field=models.TextField(
                blank=True, help_text="Apuntes médicos y observaciones"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="heart_rate",
            field=models.PositiveIntegerField(blank=True, help_text="lpm", null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="height_cm",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="oxygen_sat",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="%", null=True
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="temperature_c",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="weight_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="notes",
            field=models.TextField(blank=True, help_text="Notas internas"),
        ),
    ]
