# Generated by Django 5.2.1 on 2026-05-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="doctors/"),
        ),
    ]
