# Generated by Django 5.2.1 on 2026-05-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_doctor_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="doctors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Doctores que ofrecen este servicio. Vacío = ninguno.",
                related_name="services",
                to="catalog.doctor",
            ),
        ),
    ]
