# Generated by Django 5.2.1 on 2026-05-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_service_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address_geocoded_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se geocodificó por última vez. Se re-geocodifica si la dirección cambia.', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='address_lat',
            field=models.FloatField(blank=True, help_text='Latitud geocodificada de la dirección.', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='address_lng',
            field=models.FloatField(blank=True, help_text='Longitud geocodificada de la dirección.', null=True),
        ),
    ]
