# Generated by Django 5.2.1 on 2026-05-28 10:12

import apps.reviews.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_appointment_patient'),
        ('catalog', '0004_branch_address_geocoded_at_branch_address_lat_and_more'),
        ('patients', '0003_patient_address_neighborhood_and_more'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reviewer_name', models.CharField(max_length=150)),
                ('reviewer_email', models.EmailField(max_length=254)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(default=apps.reviews.models._default_review_token_expires)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reseña pendiente',
                'verbose_name_plural': 'Reseñas pendientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_per_patient_doctor',
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_email',
            field=models.EmailField(blank=True, help_text='Email del autor — usado para verificar reseñas anónimas y para dedupe (un email = una reseña por doctor).', max_length=254),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(blank=True, help_text='Nombre del autor (visible). Cuando hay `patient`, se llena con su nombre. En reseñas anónimas, es lo que el usuario escribió.', max_length=150),
        ),
        migrations.AlterField(
            model_name='review',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='patients.patient'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('patient__isnull', False)), fields=('patient', 'doctor'), name='unique_review_per_patient_doctor'),
        ),
        migrations.AddField(
            model_name='pendingreview',
            name='confirmed_review',
            field=models.ForeignKey(blank=True, help_text='La Review creada al confirmar este pending. Null si aún no se ha confirmado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_pending', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='pendingreview',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_reviews', to='catalog.doctor'),
        ),
    ]
